#!/usr/bin/env bash

options=(
  style=round
  width=5.0
  hidpi=on
  active_color=0xffffb454
  inactive_color=0x55f8ead2
)

[ -r "$HOME/.config/borders/bordersrc.local" ] && . "$HOME/.config/borders/bordersrc.local"

borders "${options[@]}"
