#!/usr/bin/env sh

# Solar Glass: warm sun glass, smoked bronze, cream paper, cobalt linework.
export FONT_TEXT="${FONT_TEXT:-SF Pro Text}"
export FONT_ICON="${FONT_ICON:-JetBrainsMono Nerd Font}"
export FONT_MONO="${FONT_MONO:-JetBrainsMono Nerd Font}"
export BAR_HEIGHT="${BAR_HEIGHT:-36}"
export BAR_MARGIN="${BAR_MARGIN:-8}"
export BAR_RADIUS="${BAR_RADIUS:-14}"
export ITEM_HEIGHT="${ITEM_HEIGHT:-26}"
export ITEM_RADIUS="${ITEM_RADIUS:-12}"
export POPUP_RADIUS="${POPUP_RADIUS:-18}"
export POPUP_ROW_HEIGHT="${POPUP_ROW_HEIGHT:-30}"
export POPUP_TITLE_HEIGHT="${POPUP_TITLE_HEIGHT:-34}"

export GRAPHITE="${GRAPHITE:-0xff1a1309}"
export BAR_BG="${BAR_BG:-0x34231a0f}"
export TEXT="${TEXT:-0xffffead2}"
export MUTED="${MUTED:-0xffc7b18a}"
export CREAM="${CREAM:-0xfffff3dc}"
export AMBER="${AMBER:-0xffffb454}"
export ORANGE="${ORANGE:-0xffff7a45}"
export ROSE="${ROSE:-0xffff6f61}"
export LIME="${LIME:-0xffb8e986}"
export CYAN="${CYAN:-0xff9de0ca}"
export BLUE="${BLUE:-0xff496dff}"
export PURPLE="${PURPLE:-0xffd6a4bd}"

export ITEM_BG="${ITEM_BG:-0x0affead2}"
export ITEM_BG_HOT="${ITEM_BG_HOT:-0x12ffead2}"
export ITEM_BG_OK="${ITEM_BG_OK:-0x1ab8e986}"
export ITEM_BG_WARN="${ITEM_BG_WARN:-0x36ff6f61}"
export ITEM_BG_ACTIVE="${ITEM_BG_ACTIVE:-0x30ffb454}"
export ITEM_BG_CONFIRM="${ITEM_BG_CONFIRM:-0x32ffb454}"
export ITEM_BORDER="${ITEM_BORDER:-0x14ffead2}"
export ITEM_BORDER_ACTIVE="${ITEM_BORDER_ACTIVE:-0x78ffb454}"
export ITEM_BORDER_OK="${ITEM_BORDER_OK:-0x5ab8e986}"
export ITEM_BORDER_CONFIRM="${ITEM_BORDER_CONFIRM:-0x72ffb454}"
export ITEM_BORDER_WARN="${ITEM_BORDER_WARN:-0x7aff6f61}"

export SPACE_BG="${SPACE_BG:-0x08ffead2}"
export SPACE_BORDER="${SPACE_BORDER:-0x12ffead2}"
export SPACE_ACTIVE_BG="${SPACE_ACTIVE_BG:-0x34ffb454}"
export SPACE_ACTIVE_BORDER="${SPACE_ACTIVE_BORDER:-0x80ffb454}"
export SPACE_OCCUPIED_ICON="${SPACE_OCCUPIED_ICON:-0xffffdfaa}"
export SPACE_ACTIVE_ICON="${SPACE_ACTIVE_ICON:-0xfffff3dc}"

export BRACKET_BG="${BRACKET_BG:-0x04ffead2}"
export BRACKET_BORDER="${BRACKET_BORDER:-0x0cffead2}"
export POPUP_BG="${POPUP_BG:-0x6a1a1309}"
export POPUP_BORDER="${POPUP_BORDER:-0x40ffcf86}"
export POPUP_SHADOW="${POPUP_SHADOW:-0x77110b05}"
export POPUP_TITLE_BG="${POPUP_TITLE_BG:-0x1effb454}"
export POPUP_ITEM_BG="${POPUP_ITEM_BG:-0x0effead2}"
export POPUP_ITEM_BORDER="${POPUP_ITEM_BORDER:-0x18ffead2}"
export POPUP_MUTED_BG="${POPUP_MUTED_BG:-0x06ffead2}"
export POPUP_MUTED_BORDER="${POPUP_MUTED_BORDER:-0x0affead2}"
export POPUP_BLUR="${POPUP_BLUR:-46}"
export SHADOW="${SHADOW:-0x66110b05}"
